name: Dockerfile Test
on:
  pull_request:
    branches: ["*"]
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build all Dockerfiles
        env:
          IMAGE_NAME: ${{ github.repository_owner }}/github-test
        run: |
          for file in $(find . -maxdepth 1 -type f -name 'Dockerfile*'); do
            tag=$(basename "$file" | sed 's/Dockerfile\.//')
            tag=${tag:-default}
            docker build -f "$file" -t "$IMAGE_NAME:$tag" .
          done