name: Dockerfile Test
on:
  pull_request:
    branches: ["*"]
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Build all Dockerfiles
        env:
          IMAGE_NAME: ${{ github.repository_owner }}/github-test
        run: |
          for file in $(find dockerfiles -type f -name 'Dockerfile*'); do
              filename=$(basename "$file")
              if [ "$filename" = "Dockerfile" ]; then
                tag="default"
              else
                tag="${filename#Dockerfile.}"
              fi
              docker build -f "$file" -t "$IMAGE_NAME:$tag" "$(dirname "$file")"
          done
